[[java-linkedhashmap]]
=  LinkedHashMap

[[java-linkedhashmap-overview]]
==  概述

`LinkedHashMap` 是 `Map` 接口的哈希表和链接列表实现,具有可预知的迭代顺序.此实现提供所有可选的映射操作,并允许使用 `null` 值和 `null` 键.

`LinkedHashMap` 实现与 `HashMap` 的不同之处在于,后者维护着一个运行于所有 `Entry` 的双向链接列表.此链接列表定义了迭代顺序,该迭代顺序可以是插入顺序或者是访问顺序.

[NOTE]
====
注意,此实现不是同步的.如果多个线程同时访问链接的哈希映射,而其中至少一个线程从结构上修改了该映射,则它必须保持外部同步.
====

[[java-linkedhashmap-impl]]
== LinkedHashMap 的实现

对于 `LinkedHashMap` 而言,它继承 `HashMap`， 底层使用哈希表与双向链表来保存所有元素.其基本操作与父类 `HashMap` 相似,它通过重写父类相关的方法,来实现自己的链接列表特性.下面我们来分析 `LinkedHashMap` 的源代码:

[[java-linkedhashmap-entry]]
=== Entry 元素

`LinkedHashMap` 采用的 `hash` 算法和 `HashMap` 相同,但是它重新定义了数组中保存的元素 `Entry`,该 `Entry` 除了保存当前对象的引用外,还保存了其上一个元素 `before` 和下一个元素 `after` 的引用, 他还重新定义了 `newNode` 方法，从而在哈希表的基础上又构成了双向链接列表.看源代码:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
/**
 * 双向链表的表头元素.
 */
transient LinkedHashMap.Entry<K,V> head;

/**
 * 双向链表的表尾元素.
 */
transient LinkedHashMap.Entry<K,V> tail;

/**
  * LinkedHashMap 的 Entry 元素.
  * 继承 HashMap 的 `Node` 元素,又保存了其上一个元素 before 和下一个元素 after 的引用.
  */
static class Entry<K,V> extends HashMap.Node<K,V> {
    Entry<K,V> before, after;
    Entry(int hash, K key, V value, Node<K,V> next) {
        super(hash, key, value, next);
    }
}

// Create a regular (non-tree) node
Node<K,V> newNode(int hash, K key, V value, Node<K,V> next) {
    return new Node<>(hash, key, value, next);
}
----


[[java-linkedhashmap-init]]
===  初始化

通过源代码可以看出,在 `LinkedHashMap` 的构造方法中,实际调用了父类 `HashMap` 的相关构造方法来构造一个底层存放的 `table` 数组.如:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----

/**
 * 此链接哈希映射的迭代排序方法: {@code true}
 * for access-order, {@code false} for insertion-order.
 * 此 LinkedHashMap 的迭代排序方法: true 为访问排序， false 为插入排序
 * @serial
 */
final boolean accessOrder;

// 构造一个指定初始容量和负载因子的、按照插入顺序的LinkedList
public LinkedHashMap(int initialCapacity, float loadFactor) {
    super(initialCapacity, loadFactor);
    accessOrder = false;
}

// 构造方法2，构造一个指定初始容量的LinkedHashMap，取得键值对的顺序是插入顺序
public LinkedHashMap(int initialCapacity) {
    super(initialCapacity);
    accessOrder = false;
}

// 构造方法3，用默认的初始化容量和负载因子创建一个LinkedHashMap，取得键值对的顺序是插入顺序
public LinkedHashMap() {
    super();
    accessOrder = false;
}

// 构造方法4，通过传入的map创建一个LinkedHashMap，容量为默认容量（16）和(map.zise()/DEFAULT_LOAD_FACTORY)+1的较大者，装载因子为默认值
public LinkedHashMap(Map<? extends K, ? extends V> m) {
    super();
    accessOrder = false;
    putMapEntries(m, false);
}

// 构造方法5，根据指定容量、装载因子和键值对保持顺序创建一个LinkedHashMap
public LinkedHashMap(int initialCapacity,
                 float loadFactor,
                 boolean accessOrder) {
    super(initialCapacity, loadFactor);
    this.accessOrder = accessOrder;
}
----

我们已经知道 LinkedHashMap 的 `Entry` 元素继承 `HashMap` 的 `Node`,提供了双向链表 的功能.在上述 `HashMap` 的构造器中,最后会调用 `init()` 方法,进行相关的初始化,这个方法在 `HashMap` 的实现中并无意义,只是提供给子类实现相关的初始化调用.

[[java-linkedhashmap-set]]
===  存储

我们之前在介绍 HashMap 储存时提到过，在 HashMap 的存储中有两个回调方法 `afterNodeAccess` 和 `afterNodeInsertion` 。`LinkedHashMap` 实现了这两个方法

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
// 当存在相同元素时，覆盖回调
void afterNodeAccess(Node<K,V> e) { // move node to last
    LinkedHashMap.Entry<K,V> last;
    // 如果为访问顺序排序
    if (accessOrder && (last = tail) != e) {
        //
        LinkedHashMap.Entry<K,V> p =
            (LinkedHashMap.Entry<K,V>)e, b = p.before, a = p.after;
        p.after = null;
        if (b == null)
            head = a;
        else
            b.after = a;
        if (a != null)
            a.before = b;
        else
            last = b;
        if (last == null)
            head = p;
        else {
            p.before = last;
            last.after = p;
        }
        tail = p;
        ++modCount;
    }
}

// afterNodeInsertion 会将链表头的 Node (最早插入的) 删除。在j dk1.8 中， removeEldestEntry 默认返回false，所以，默认情况下 afterNodeInsertion 不生效。
void afterNodeInsertion(boolean evict) { // possibly remove eldest
    LinkedHashMap.Entry<K,V> first;
    if (evict && (first = head) != null && removeEldestEntry(first)) {
        K key = first.key;
        removeNode(hash(key), key, null, false, true);
    }
}
----

那么 `LinkedHashMap` 是如何保证元素顺序的呢。主要还是在穿件节点的时候，`LinkedHashMap` 重新实现了 `newNode` 方法

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
Node<K,V> newNode(int hash, K key, V value, Node<K,V> e) {
    LinkedHashMap.Entry<K,V> p =
        new LinkedHashMap.Entry<K,V>(hash, key, value, e);
    linkNodeLast(p);
    return p;
}

// 添加到链表尾部
private void linkNodeLast(LinkedHashMap.Entry<K,V> p) {
    LinkedHashMap.Entry<K,V> last = tail;
    tail = p;
    if (last == null)
        head = p;
    else {
        p.before = last;
        last.after = p;
    }
}
----

[[java-linkedhashmap-get]]
===  获取

`LinkedHashMap` 重写了父类 `HashMap` 的 `get` 方法,实际在调用父类 `getNode()` 方法取得查找的元素后,再判断当排序模式 `accessOrder` 为 `true` 时,记录访问顺序,将最新访问的元素添加到双向链表的表头,并从原来的位置删除.由于的链表的增加、删除操作是常量级的,故并不会带来性能的损失.

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
public V get(Object key) {
    Node<K,V> e;
    if ((e = getNode(hash(key), key)) == null)
        return null;
    if (accessOrder)
        afterNodeAccess(e);
    return e.value;
}
----

[[java-linkedhashmap-sort]]
==  排序模式

`LinkedHashMap` 定义了排序模式 `accessOrder`,该属性为 `boolean` 型变量,对于访问顺序,为 `true`;对于插入顺序,则为 `false`.

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
private final boolean accessOrder;
----

一般情况下,不必指定排序模式,其迭代顺序即为默认为插入顺序.看 `LinkedHashMap` 的构造方法,如:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
public LinkedHashMap(int initialCapacity, float loadFactor) {
    super(initialCapacity, loadFactor);
    accessOrder = false;
}
----

这些构造方法都会默认指定排序模式为插入顺序.如果你想构造一个 `LinkedHashMap`, 并打算按从近期访问最少到近期访问最多的顺序(即访问顺序)来保存元素,那么请使用下面的构造方法构造 `LinkedHashMap`:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
public LinkedHashMap(int initialCapacity,
    float loadFactor,
    boolean accessOrder) {
    super(initialCapacity, loadFactor);
    this.accessOrder = accessOrder;
}
----

该哈希映射的迭代顺序就是最后访问其条目的顺序,这种映射很适合构建 `LRU` 缓存.`LinkedHashMap` 提供了 `removeEldestEntry(Map.Entry<K,V> eldest)` 方法,在将新条目插入到映射后,`put` 和 `putAll` 将调用此方法.该方法可以提供在每次添加新条目时移除最旧条目的实现程序,默认返回 `false`,这样,此映射的行为将类似于正常映射,即永远不能移除最旧的元素.

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
protected boolean removeEldestEntry(Map.Entry<K,V> eldest) {
    return false;
}
----

此方法通常不以任何方式修改映射,相反允许映射在其返回值的指引下进行自我修改. 如果用此映射构建 `LRU` 缓存,则非常方便,它允许映射通过删除旧条目来减少内存损耗.

例如: 重写此方法,维持此映射只保存 `100` 个条目的稳定状态,在每次添加新条目时删除最旧的条目.

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
private static final int MAX_ENTRIES = 100;
protected boolean removeEldestEntry(Map.Entry eldest) {
    return size() > MAX_ENTRIES;
}
----

[[java-linkedhashmap-qa]]
==  Q&A


[[java-linkedhashmap-extend]]
==  扩展
